### ISSUE TITLE
?????????????????????????????

### ISSUE THREAD

**Issue by b-y-f** [simbazhu/C-Primer-Plus-Programming-Exercises-And-Answers#1]

**Comment by yifanzhu1592** [comment]
Hi, what's up?

**Comment by b-y-f** [comment]
9.6 cant pass my complier textbook never use this kind of function. fun(int &i)

**Comment by yifanzhu1592** [comment]
I just checked the program. I don't know why it can't pass your compiler, can you share a screenshot of what the compiler says?

And "&i" means the address of the variable i, "i" here is a pointer that can point to different values, so you could change its value and the new value would be kept to the pointer even after the function finishes.
